# Generated by Django 2.0.4 on 2018-05-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='task_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='taskInfo',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_category', models.CharField(max_length=50)),
                ('task_rank', models.CharField(max_length=50)),
                ('principle_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=30)),
                ('userIdentity', models.IntegerField()),
                ('userPassword', models.CharField(default='123456', max_length=20)),
                ('userSex', models.CharField(max_length=10)),
                ('userEduBack', models.CharField(max_length=10)),
                ('userTechPost', models.CharField(default='讲师', max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teacher_student',
            unique_together={('teacher', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='task_user',
            unique_together={('task_id', 'user_id')},
        ),
    ]
