# Generated by Django 2.0.4 on 2018-06-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('b1_1', models.CharField(default=0, max_length=10)),
                ('b1_2', models.CharField(default=0, max_length=10)),
                ('b1_3', models.CharField(default=0, max_length=10)),
                ('b2', models.CharField(default=0, max_length=10)),
                ('b3', models.CharField(default=0, max_length=10)),
                ('b4', models.CharField(default=0, max_length=10)),
                ('b5', models.CharField(default=0, max_length=10)),
                ('b6', models.CharField(default=0, max_length=10)),
                ('b7', models.CharField(default=0, max_length=10)),
                ('b8', models.CharField(default=0, max_length=10)),
                ('b9', models.CharField(default=0, max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('remaining', models.CharField(max_length=10)),
            ],
        ),
    ]
