# Generated by Django 2.0.4 on 2018-06-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('to_credit_card', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
