# Generated by Django 2.0.4 on 2018-06-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_budget_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_out',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
