# Generated by Django 2.0.4 on 2018-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180603_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.IntegerField()),
                ('purchase_time', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('scrap_time', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('task_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('detail_info', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('if_ratify', models.IntegerField()),
                ('task_id', models.IntegerField()),
            ],
        ),
    ]
