# Generated by Django 2.0.4 on 2018-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_property_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='scrap_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
