# Generated by Django 2.0.4 on 2018-06-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180611_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='name',
            new_name='property_name',
        ),
    ]
