# Generated by Django 2.0.4 on 2018-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180611_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
