# Generated by Django 2.0.4 on 2018-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_journalarticle_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMonograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author_id', models.IntegerField()),
                ('editor', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('publish_time', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('task_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50)),
                ('category', models.IntegerField()),
                ('confer_name', models.CharField(max_length=50)),
                ('confer_time', models.CharField(max_length=50)),
                ('publish_time', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('task_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftwarePatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author_id', models.IntegerField()),
                ('register_num', models.CharField(max_length=50)),
                ('method', models.IntegerField()),
                ('finish_time', models.CharField(max_length=50)),
                ('task_id', models.IntegerField()),
            ],
        ),
    ]
